In [1]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

Using TensorFlow backend.
/Users/santoshsaxena/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/santoshsaxena/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/santoshsaxena/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/santoshsaxena/anaconda3/l

In [2]:
data = pd.read_csv("Desktop/Air_Quality_Monitoring_Data.csv")
data_new = data.dropna()

In [3]:
no2 = data_new.iloc[0:60000,3:4].values
o3_1hrs = data_new.iloc[0:60000,4:5].values
o3_4hrs = data_new.iloc[0:60000,5:6].values
co = data_new.iloc[0:60000,6:7].values
pm10 = data_new.iloc[0:60000,7:8].values
pm2 = data_new.iloc[0:60000,8:9].values
aqi_co = data_new.iloc[0:60000,9:10].values
aqi_no2 = data_new.iloc[0:60000,10:11].values
aqi_o3_1hrs = data_new.iloc[0:60000,11:12].values
aqi_o3_4hrs = data_new.iloc[0:60000,12:13].values
aqi_pm10 = data_new.iloc[0:60000, 13:14].values
aqi_pm2 = data_new.iloc[0:60000, 14:15].values
aqi_site = data_new.iloc[0:60000 , 15:16].values

In [4]:
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(64, input_dim=1, kernel_initializer='normal', activation='relu'))
    model.add(Dense(32, input_dim=1, kernel_initializer='normal', activation='relu'))
    model.add(Dense(16, input_dim=1, kernel_initializer='normal', activation='relu'))
    model.add(Dense(8, input_dim=1, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='normal'))
    # Compile model
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [36]:
no2_model = baseline_model()

In [37]:
no2_model.fit(no2[0:40000],aqi_no2[0:40000],epochs=  10)

Epoch 1/10
40000/40000 [==============================] - 6s 144us/step - loss: 41.8807
Epoch 2/10
40000/40000 [==============================] - 4s 106us/step - loss: 35.3269
Epoch 3/10
40000/40000 [==============================] - 4s 104us/step - loss: 3.4905
Epoch 4/10
40000/40000 [==============================] - 4s 103us/step - loss: 2.0059
Epoch 5/10
40000/40000 [==============================] - 4s 107us/step - loss: 1.9925
Epoch 6/10
40000/40000 [==============================] - 4s 107us/step - loss: 1.9869
Epoch 7/10
40000/40000 [==============================] - 4s 105us/step - loss: 1.9810
Epoch 8/10
40000/40000 [==============================] - 4s 110us/step - loss: 2.0046
Epoch 9/10
40000/40000 [==============================] - 4s 106us/step - loss: 1.9866
Epoch 10/10
40000/40000 [==============================] - 5s 113us/step - loss: 1.9904


In [38]:
co_model = baseline_model()
co_model.fit(co[0:40000], aqi_co[0:40000], epochs = 10)

Epoch 1/10
40000/40000 [==============================] - 7s 185us/step - loss: 12.3999
Epoch 2/10
40000/40000 [==============================] - 4s 108us/step - loss: 0.0869
Epoch 3/10
40000/40000 [==============================] - 4s 107us/step - loss: 0.0843
Epoch 4/10
40000/40000 [==============================] - 4s 108us/step - loss: 0.0902
Epoch 5/10
40000/40000 [==============================] - 5s 115us/step - loss: 0.1265
Epoch 6/10
40000/40000 [==============================] - 4s 107us/step - loss: 0.0801
Epoch 7/10
40000/40000 [==============================] - 4s 110us/step - loss: 0.1045
Epoch 8/10
40000/40000 [==============================] - 5s 117us/step - loss: 0.1522
Epoch 9/10
40000/40000 [==============================] - 4s 110us/step - loss: 0.1093
Epoch 10/10
40000/40000 [==============================] - 4s 112us/step - loss: 0.0725


In [20]:
pm2_model = baseline_model()
pm2_model.fit(pm2[0:40000], aqi_pm2[0:40000] , epochs = 2)

Epoch 1/2
40000/40000 [==============================] - 5s 132us/step - loss: 9695.5058
Epoch 2/2
40000/40000 [==============================] - 4s 105us/step - loss: 0.6312


In [19]:
pm10_model = baseline_model()
pm10_model.fit(pm10[0:40000], aqi_pm10[0:40000], epochs = 2)

Epoch 1/2
40000/40000 [==============================] - 6s 151us/step - loss: 2117.1029
Epoch 2/2
40000/40000 [==============================] - 4s 100us/step - loss: 0.2759


In [59]:
o31hrs_model = baseline_model()
o31hrs_model.fit(o3_1hrs[0:40000] , aqi_o3_1hrs[0:40000], epochs = 10) 

Epoch 1/10
40000/40000 [==============================] - 6s 145us/step - loss: 172.3454
Epoch 2/10
40000/40000 [==============================] - 5s 114us/step - loss: 4.6217
Epoch 3/10
40000/40000 [==============================] - 4s 108us/step - loss: 4.6182
Epoch 4/10
40000/40000 [==============================] - 5s 113us/step - loss: 4.6424
Epoch 5/10
40000/40000 [==============================] - 4s 112us/step - loss: 4.6586
Epoch 6/10
40000/40000 [==============================] - 4s 108us/step - loss: 4.6425
Epoch 7/10
40000/40000 [==============================] - 4s 108us/step - loss: 4.6352
Epoch 8/10
40000/40000 [==============================] - 4s 109us/step - loss: 4.6454
Epoch 9/10
40000/40000 [==============================] - 5s 114us/step - loss: 4.6200
Epoch 10/10
40000/40000 [==============================] - 4s 110us/step - loss: 4.6352


In [10]:
o3_model = baseline_model()
o3_model.fit(o3_4hrs[0:40000], aqi_o3_4hrs[0:40000], epochs = 10)

Epoch 1/10
40000/40000 [==============================] - 5s 134us/step - loss: 307.2348
Epoch 2/10
40000/40000 [==============================] - 4s 100us/step - loss: 61.1080
Epoch 3/10
40000/40000 [==============================] - 4s 96us/step - loss: 7.5187
Epoch 4/10
40000/40000 [==============================] - 4s 96us/step - loss: 7.5263
Epoch 5/10
40000/40000 [==============================] - 4s 96us/step - loss: 7.5480
Epoch 6/10
40000/40000 [==============================] - 4s 98us/step - loss: 7.5504
Epoch 7/10
40000/40000 [==============================] - 4s 101us/step - loss: 7.5457
Epoch 8/10
40000/40000 [==============================] - 4s 98us/step - loss: 7.5673
Epoch 9/10
40000/40000 [==============================] - 4s 97us/step - loss: 7.5504
Epoch 10/10
40000/40000 [==============================] - 4s 112us/step - loss: 7.5426


In [39]:
PM2 = pm2_model.evaluate(pm2[40000:60000],aqi_pm2[40000:60000])

20000/20000 [==============================] - 1s 48us/step


In [40]:
PM10 = pm10_model.evaluate(pm10[40000:60000],aqi_pm10[40000:60000])

20000/20000 [==============================] - 1s 45us/step


In [41]:
O3 = o3_model.evaluate(o3_4hrs[40000:60000],aqi_o3_4hrs[40000:60000])

20000/20000 [==============================] - 1s 41us/step


In [42]:
CO = co_model.evaluate(co[40000:60000],aqi_co[40000:60000])

20000/20000 [==============================] - 1s 67us/step


In [43]:
NO2 = no2_model.evaluate(no2[40000:60000], aqi_no2[40000:60000])

20000/20000 [==============================] - 2s 82us/step


In [60]:
O3_1hrs = o31hrs_model.evaluate(o3_1hrs[40000:60000], aqi_o3_1hrs[40000:60000])

20000/20000 [==============================] - 2s 90us/step


In [61]:
print(PM2)
print(PM10)
print(CO)
print(NO2)
print(PM2)
print(PM10)
print(O3_1hrs)

1.5674225821495056
0.5613231887817383
0.06900717656612396
3.5960229131698607
1.5674225821495056
0.5613231887817383
7.201528022766113


In [62]:
no2_pred = no2_model.predict(no2[40000:60000])
co_pred = co_model.predict(co[40000:60000])
pm2_pred = pm2_model.predict(pm2[40000:60000])
pm10_pred = pm10_model.predict(pm10[40000:60000])
o3_pred = o3_model.predict(o3_4hrs[40000:60000])
o3_1hrs_pred = o31hrs_model.predict(o3_1hrs[40000:60000])

In [63]:
print(no2_pred)
print(aqi_no2)

[[0.6332086]
 [0.6332086]
 [0.6332086]
 ...
 [0.6332086]
 [0.6332086]
 [7.355432 ]]
[[ 0.]
 [ 5.]
 [15.]
 ...
 [ 0.]
 [ 0.]
 [ 5.]]


In [64]:
print(co_pred)
print(aqi_co)

[[1.3153349 ]
 [1.6813256 ]
 [0.9522552 ]
 ...
 [0.9904859 ]
 [0.95225525]
 [1.315335  ]]
[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [1.]]


In [65]:
print(pm2_pred)
print(aqi_pm2)

[[27.865477 ]
 [15.865658 ]
 [19.865597 ]
 ...
 [11.865718 ]
 [23.865538 ]
 [ 3.8658392]]
[[14.]
 [25.]
 [14.]
 ...
 [10.]
 [24.]
 [ 2.]]


In [66]:
print(pm10_pred)
print(aqi_pm10)

[[19.914616 ]
 [ 9.910512 ]
 [19.914616 ]
 ...
 [ 5.908871 ]
 [19.914614 ]
 [ 3.9080513]]
[[12.]
 [16.]
 [13.]
 ...
 [ 7.]
 [20.]
 [ 5.]]


In [67]:
print(o3_pred)
print(aqi_o3_4hrs)

[[24.975185]
 [24.975185]
 [37.21577 ]
 ...
 [24.975185]
 [12.734603]
 [24.975185]]
[[34.]
 [32.]
 [19.]
 ...
 [22.]
 [14.]
 [26.]]


In [68]:
print(aqi_o3_1hrs)
print(o3_1hrs_pred)

[[24.]
 [20.]
 [ 2.]
 ...
 [18.]
 [12.]
 [21.]]
[[18.70558 ]
 [18.70558 ]
 [18.70558 ]
 ...
 [18.70558 ]
 [ 9.132311]
 [18.70558 ]]
